apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
    - "*"
  gateways:
    - swan-front-blue-green/frontend
  http:
    - match:
      route:
        - destination:
            host: frontend-active
            port:
              number: 80