apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc-bleu-green
spec:
  hosts:
    - "*"
  gateways:
    - swan-front-blue-green/istio-rollout-gateway-bleu-green
  http:
    - match:
      route:
        - destination:
            host: istio-rollout-active
            port:
              number: 80